### ISSUE TITLE
segfault on missing /usr/share/nwg-look/main.glade

### ISSUE THREAD

**Issue by hboetes** [nwg-piotr/nwg-look#17]
I went a bit too fast whilst installing nwg-look and got the error below. Of course after installing `main.glade` at the right location this problem went away.

```
INFO[0000] input-feedback-sounds: false                 

(nwg-look:20058): Gtk-ERROR **: 22:09:16.247: failed to add UI: Failed to open file “/usr/share/nwg-look/main.glade”: No such file or directory
SIGTRAP: trace trap
PC=0x7f87a54a9e10 m=4 sigcode=128
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x5bbee0, 0xc0000e5c50)
	/usr/lib/golang/src/runtime/cgocall.go:157 +0x5c fp=0xc0000e5c28 sp=0xc0000e5bf0 pc=0x48523c
github.com/gotk3/gotk3/gtk._Cfunc_gtk_builder_new_from_file(0x1f4abd0)
	_cgo_gotypes.go:6402 +0x49 fp=0xc0000e5c50 sp=0xc0000e5c28 pc=0x56cd09
github.com/gotk3/gotk3/gtk.BuilderNewFromFile({0x689f03?, 0x7?})
	/home/han/go/pkg/mod/github.com/gotk3/gotk3@v0.6.1/gtk/gtk_since_3_10.go:876 +0x67 fp=0xc0000e5ca8 sp=0xc0000e5c50 pc=0x58a207
main.main()
	/usr/pkgmk/work/nwg-look/src/nwg-look/main.go:333 +0x62c fp=0xc0000e5f80 sp=0xc0000e5ca8 pc=0x599c8c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x212 fp=0xc0000e5fe0 sp=0xc0000e5f80 pc=0x4b6fd2
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000e5fe8 sp=0xc0000e5fe0 pc=0x4e2721

rax    0x0
rbx    0x1
rcx    0xf
rdx    0x7f8770002
rdi    0x7
rsi    0x7f87700008e0
rbp    0x7f87792a34c0
rsp    0x7f87792a3420
r8     0x7f8770002fd0
r9     0x73
r10    0x0
r11    0xcdcd34f3ae091e21
r12    0x6
r13    0x0
r14    0x7f87a5584d00
r15    0x7f87a5584d90
rip    0x7f87a54a9e10
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by nwg-piotr** [comment]
Yeah, it's damned difficult to predict all the unexpected things a user might to with a program. :rofl:
